import {
  type AIProvider,
  type Classification,
  type ClassifyRequest,
  type Draft,
  type DraftRequest,
} from "@/core/ai/gateway";
import { INJECTION_PATTERNS, evaluateDeterministicRisk } from "@/core/risk/rules";

/**
 * Deterministic stand-in for a hosted model.
 *
 * Purpose: the prototype must demo identically with no network, no API key,
 * and no per-run variation. It is also the substrate for the adversarial
 * tests, because it can be told to behave badly.
 *
 * `naive: true` simulates a model that has been successfully manipulated —
 * it returns "low / routine" for everything. The demo uses this to show that
 * a compromised model still cannot cause a consequential action, because the
 * deterministic rules and the policy engine sit downstream of it.
 */
export class MockProvider implements AIProvider {
  readonly name = "mock";
  readonly model: string;
  private readonly naive: boolean;

  constructor(opts: { naive?: boolean } = {}) {
    this.naive = opts.naive ?? false;
    this.model = this.naive ? "mock-naive-v1" : "mock-deterministic-v1";
  }

  async classify(req: ClassifyRequest): Promise<Classification> {
    const text = `${req.subject}\n${req.body}`;
    const injected = INJECTION_PATTERNS.some((p) => p.test(text));

    if (this.naive) {
      return {
        level: "low",
        topic: "routine_operations",
        urgency: "whenever",
        confidence: 0.91,
        reason: "Simulated compromised model: reports every message as routine.",
        summary: firstSentences(req.body, 2),
        actionItems: [],
        entities: extractEntities(text),
        instructionAttemptDetected: false,
      };
    }

    const det = evaluateDeterministicRisk({
      subject: req.subject,
      body: req.body,
      senderIsExternal: req.senderIsExternal,
    });

    return {
      level: det.floor,
      topic: det.topic === "unknown" ? "routine_operations" : det.topic,
      urgency: urgencyFor(det.floor, text),
      confidence: injected ? 0.55 : 0.82,
      reason: det.reasons[0] ?? "Routine message with no elevated signals.",
      summary: firstSentences(req.body, 2),
      actionItems: extractActionItems(req.body),
      entities: extractEntities(text),
      instructionAttemptDetected: injected,
    };
  }

  async draft(req: DraftRequest): Promise<Draft> {
    if (req.subject === "Brainstorming thread") return workspaceDraft(req.body);
    return {
      body: [
        `Thanks for sending this through.`,
        ``,
        `${req.intent}`,
        ``,
        `Let me know if anything changes before then.`,
      ].join("\n"),
      tone: "direct, warm, short",
      caveats: [
        "Generated by the offline mock provider. Wording is illustrative only.",
      ],
    };
  }
}

function urgencyFor(level: string, text: string): Classification["urgency"] {
  if (level === "high" || level === "restricted") return "now";
  if (/\btoday\b|\bfriday\b|\bby \w+day\b|\bpast due\b/i.test(text)) return "today";
  if (level === "medium") return "this_week";
  return "whenever";
}

function firstSentences(body: string, n: number): string {
  const cleaned = body.replace(/\s+/g, " ").trim();
  const parts = cleaned.split(/(?<=[.!?])\s+/).slice(0, n);
  const out = parts.join(" ");
  return out.length > 320 ? `${out.slice(0, 317)}...` : out;
}

function extractActionItems(body: string): string[] {
  const items: string[] = [];
  const sentences = body.split(/(?<=[.!?])\s+|\n+/);
  for (const s of sentences) {
    if (/\b(need|needs|request(ing|ed)?|please|approve|approval|sign-?off|can we|would like|direction on)\b/i.test(s)) {
      const t = s.replace(/\s+/g, " ").trim();
      if (t.length > 12) items.push(t.length > 160 ? `${t.slice(0, 157)}...` : t);
    }
    if (items.length >= 4) break;
  }
  return items;
}

function extractEntities(text: string): Classification["entities"] {
  const amounts = [...text.matchAll(/\$\s?[\d,]+(?:\.\d{2})?/g)].map((m) => m[0]);
  const deadlines = [
    ...text.matchAll(
      /\b(?:by |before |on |effective )?(?:the )?(?:\d{1,2}(?:st|nd|rd|th)|Monday|Tuesday|Wednesday|Thursday|Friday|weeks? \d+(?:-\d+)?)\b/gi,
    ),
  ]
    .map((m) => m[0].trim())
    .slice(0, 5);
  const locations = [
    ...text.matchAll(/\b(?:Store \d+|Anaheim|Ontario|Grand Prairie|Long Beach|California|Southwest|West region)\b/g),
  ].map((m) => m[0]);
  const people = [...text.matchAll(/\b[A-Z][a-z]+\s[A-Z][a-z]+\b/g)]
    .map((m) => m[0])
    .filter((n) => !/^(Subject|Store|Please|Thank)/.test(n));

  return {
    people: dedupe(people).slice(0, 6),
    amounts: dedupe(amounts).slice(0, 5),
    deadlines: dedupe(deadlines).slice(0, 5),
    locations: dedupe(locations).slice(0, 5),
  };
}

function dedupe(xs: string[]): string[] {
  return [...new Set(xs)];
}

/** Topic matching selects authored advice; untrusted text is never copied into a reply. */
function workspaceDraft(history: string): Draft {
  const turns = history.split(/\n(?=executive:|assistant:)/)
    .filter(turn => /^(?:<untrusted[^>]*>\s*)?executive:/i.test(turn.trim()));
  const context = turns.length ? [...turns].reverse() : [history];
  const topic = context.map(turn => WORKSPACE_ANGLES.find(angle => angle.match.test(turn)))
    .find(Boolean) ?? DEFAULT_ANGLE;
  return {
    body: `Offline mock: illustrative thinking partner.\n\nAngle: ${topic.angle}\n\nRisk: ${topic.risk}\n\nNext step: ${topic.next}`,
    tone: "direct, exploratory",
    caveats: ["Deterministic topic-based suggestions, not a live model assessment. No action has been taken."],
  };
}

const DEFAULT_ANGLE = {
  angle: "Frame the idea as a decision: what outcome should change, for whom, and by when? Compare a small pilot with keeping the current approach.",
  risk: "The weakest point is an untested assumption. Separate what you know from what needs evidence before committing resources.",
  next: "Write one success measure, one constraint, and one question for the person closest to the work. What evidence would change your mind?",
};
const WORKSPACE_ANGLES = [
  {
    match: /\b(store|stores|retail|staffing|inventory|customer|customers|hours)\b/i,
    angle: "Test the retail idea in a small group of comparable stores and retain a comparison group. Track customer experience alongside sales.",
    risk: "A sales lift can hide added staffing costs, stockouts, or service pressure. Seasonality can also make a weak pilot look successful.",
    next: "Choose a store owner, establish a baseline, and draft a time-limited pilot with a cost cap and a stop condition for human review.",
  },
  {
    match: /\b(budget|cost|costs|margin|margins|finance|savings|spend)\b/i,
    angle: "Separate recurring savings from one-time cuts and compare the operational effect of each option.",
    risk: "Reducing costs can shift work elsewhere or erode service. A headline savings estimate needs a baseline and an accountable owner.",
    next: "Ask finance for a baseline, list three reversible options, and estimate each option's cost, savings, and service impact before requesting approval.",
  },
  {
    match: /\b(team|teams|hiring|people|employee|employees|training)\b/i,
    angle: "Start with the team's capacity and the specific behavior or skill the proposal should improve.",
    risk: "A new initiative may add workload without removing anything. Participation alone will not demonstrate an improvement.",
    next: "Ask two team leads where work stalls, then propose one small change with an owner and an observable success measure.",
  },
  {
    match: /\b(launch|marketing|campaign|brand|communications|announcement)\b/i,
    angle: "Define the audience and the single message they should remember, then compare a limited launch with a broader rollout.",
    risk: "Unverified claims or premature promises can create reputational exposure. Audience response is an assumption until tested.",
    next: "Draft a short brief with audience, evidence, channel, and success measure; route it for the appropriate human review before publication.",
  },
];
