/**
 * Generates docs/EVALUATION.md.
 *
 * Run: npm run evaluate
 *
 * The output is a client artifact. It is written for someone deciding whether
 * to run a pilot, not for a log reader, so it leads with the number that
 * decides that question and states its own limits.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { SurfaceSignalProvider } from "../src/core/ai/providers/surface.ts";
import { runAll, type ModeReport } from "../src/core/services/evaluate.ts";
import { EVAL_SET } from "../src/data/eval-set.ts";
import { POLICY_VERSION } from "../src/core/policy/engine.ts";
import { PROMPT_VERSION } from "../src/core/ai/gateway.ts";

const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

const FAMILY_LABELS: Record<string, string> = {
  routine: "Routine and ordinary approvals",
  buried_crisis: "Crisis buried in a routine thread",
  fraud_approval: "Approval request that is a fraud attempt",
  casual_legal: "Legal or press matter phrased casually",
  urgent_promo: "Promotional message using urgent language",
  mnpi: "Material non-public information",
  injection: "Prompt injection",
  scheduling: "Scheduling",
  publication: "External publication",
};

function modeTable(r: ModeReport): string {
  return [
    `| Metric | Value |`,
    `|---|---|`,
    `| Cases | ${r.total} |`,
    `| Genuinely high-risk or restricted | ${r.highRiskTotal} |`,
    `| **False-safe rate** | **${pct(r.falseSafeRate)}** (${r.falseSafeCount} of ${r.highRiskTotal}) |`,
    `| High-risk recall | ${pct(r.highRiskRecall)} |`,
    `| Over-escalation rate | ${pct(r.overEscalationRate)} |`,
    `| Topic accuracy | ${pct(r.topicAccuracy)} |`,
    `| Policy agreement | ${pct(r.policyAgreement)} |`,
  ].join("\n");
}

function familyTable(reports: { rules: ModeReport; model: ModeReport; fused: ModeReport }): string {
  const families = Object.keys(reports.fused.byFamily).sort();
  const rows = families.map((f) => {
    const label = FAMILY_LABELS[f] ?? f;
    const cells = (["rules", "model", "fused"] as const).map((m) => {
      const b = reports[m].byFamily[f];
      return b ? pct(b.recall) : "—";
    });
    return `| ${label} | ${reports.fused.byFamily[f].total} | ${cells.join(" | ")} |`;
  });
  return [
    `| Case family | Cases | Rules only | Model only | Fused |`,
    `|---|---|---|---|---|`,
    ...rows,
  ].join("\n");
}

function falseSafeDetail(r: ModeReport): string {
  if (r.falseSafeIds.length === 0) {
    return "None. Every genuinely high-risk message was rated high or above.\n";
  }
  const rows = r.cases
    .filter((c) => c.falseSafe)
    .map((c) => {
      const source = EVAL_SET.find((e) => e.id === c.id);
      return `| ${c.id} | ${FAMILY_LABELS[c.family] ?? c.family} | ${c.expectedLevel} | ${c.actualLevel} | ${source?.note ?? ""} |`;
    });
  return [
    `| Case | Family | Should be | Was rated | What it is |`,
    `|---|---|---|---|---|`,
    ...rows,
  ].join("\n");
}

async function main(): Promise<void> {
  const provider = new SurfaceSignalProvider();
  const reports = await runAll({ provider });

  const md = `# Evaluation

*Generated by \`npm run evaluate\` from \`src/data/eval-set.ts\`. Policy version
${POLICY_VERSION}, prompt version ${PROMPT_VERSION}. All data is synthetic.*

---

## The number that matters

**False-safe rate: ${pct(reports.fused.falseSafeRate)}** in the configuration that ships.

A false-safe is a genuinely high-risk message that the system rated medium or
lower. It is the only error in this system that can cause harm. Every other
error costs a person thirty seconds of review, so we accept a high
over-escalation rate (${pct(reports.fused.overEscalationRate)}) to keep this
number where it is.

${reports.fused.falseSafeCount === 0
  ? "No high-risk message in the set was rated below high."
  : `${reports.fused.falseSafeCount} of ${reports.fused.highRiskTotal} high-risk messages were rated below high. They are listed in full below; none are hidden.`}

---

## What each layer contributes

${familyTable(reports)}

*Recall is the share of genuinely high-risk cases in that family rated high or
above. "Rules only" runs the deterministic rules with no model. "Model only"
removes the rules. "Fused" is \`max(rules, model)\`, which is production.*

The point of this table is the rows where the model-only column is low and the
fused column is not. Those are the cases the rules layer catches and an unaided
model does not: a fatality in a metrics roll-up, a subpoena described as a
paperwork question, an invoice-fraud attempt phrased politely. The rules
contribute nothing on the routine rows, which is the correct behaviour — a
floor should be invisible until something falls.

---

## Rules only

${modeTable(reports.rules)}

**False-safes:**

${falseSafeDetail(reports.rules)}

## Model only

${modeTable(reports.model)}

**False-safes:**

${falseSafeDetail(reports.model)}

## Fused (production)

${modeTable(reports.fused)}

**False-safes:**

${falseSafeDetail(reports.fused)}

---

## How to read these numbers honestly

**What this evaluation establishes.** That the deterministic layer raises risk
on cases where surface reading does not, that fusion never rates a message
below either layer alone, and that the policy engine turns those ratings into
the outcome a human expects ${pct(reports.fused.policyAgreement)} of the time.

**What it does not establish.** Four things, stated plainly because the client's
IT review will find them anyway:

1. **The model arm is a stand-in.** \`SurfaceSignalProvider\` classifies from
   tone, stated urgency, and framing. It reproduces the failure mode we care
   about — a serious fact stated calmly reads as routine — but it is not a
   measurement of any specific hosted model. Re-run this against the real
   provider before quoting the model-only column to anyone. That is one
   argument change in \`scripts/evaluate.ts\`.
2. **The set is written by the same people who wrote the rules.** ${EVAL_SET.length}
   cases, all synthetic. A set written by the client's own operators, from the
   shapes of message they actually receive, would be a stronger test and is the
   first thing to build in a pilot.
3. **Summary faithfulness is not measured here.** It requires a person reading
   summaries against source messages. The harness reports risk, topic, and
   policy agreement, which are machine-checkable. Faithfulness is a manual
   spot-check and belongs in the pilot's first week.
4. **Ground truth is a judgement.** Each label is what a competent chief of
   staff would assign. Where the client disagrees with a label, the label is
   what should change, not the rule — and that disagreement is the most useful
   thing this artifact can produce.

**The safety argument does not rest on these numbers.** Even at a false-safe
rate of 100%, no consequential action occurs: the policy engine requires a
human approval for every send, every calendar write, and every publication,
and a mis-rated message becomes a mis-prioritized item in a queue rather than
an action taken. The evaluation measures how good the triage is. The controls
are what make the triage safe to be wrong about.
`;

  mkdirSync("docs", { recursive: true });
  writeFileSync("docs/EVALUATION.md", md);

  console.log(`fused false-safe rate: ${pct(reports.fused.falseSafeRate)}`);
  console.log(`rules false-safe rate: ${pct(reports.rules.falseSafeRate)}`);
  console.log(`model false-safe rate: ${pct(reports.model.falseSafeRate)}`);
  console.log("wrote docs/EVALUATION.md");
}

void main();
